In [12]:
import pandas as pd
import numpy as np

## Extracting features of 2018 movies from Wikipedia

In [13]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2018"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [14]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1752420719.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [15]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.
0,J A N U A R Y,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2],NaN
1,J A N U A R Y,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3],NaN
2,J A N U A R Y,5,Stratton,Momentum Pictures / GFM Films,"Simon West (director); Duncan Falconer, Warren...",[4],NaN
3,J A N U A R Y,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5],NaN
4,J A N U A R Y,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6],NaN
...,...,...,...,...,...,...,...
270,D E C E M B E R,25,Holmes & Watson,Columbia Pictures / Gary Sanchez Productions,Etan Cohen (director/screenplay); Will Ferrell...,NaN,[164]
271,D E C E M B E R,25,Vice,Annapurna Pictures / Plan B Entertainment,Adam McKay (director/screenplay); Christian Ba...,NaN,[137]
272,D E C E M B E R,25,On the Basis of Sex,Focus Features,Mimi Leder (director); Daniel Stiepleman (scre...,NaN,[230]
273,D E C E M B E R,25,Destroyer,Annapurna Pictures,"Karyn Kusama (director); Phil Hay, Matt Manfre...",NaN,[263]
274,D E C E M B E R,28,Black Mirror: Bandersnatch,Netflix,David Slade (director); Charlie Brooker (scree...,NaN,[264]

In [16]:
!pip install tmdbv3api

Requirement already satisfied: tmdbv3api in c:\users\yassine\anaconda3\lib\site-packages (1.7.7)
Requirement already satisfied: requests in c:\users\yassine\anaconda3\lib\site-packages (from tmdbv3api) (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\yassine\anaconda3\lib\site-packages (from requests->tmdbv3api) (1.26.14)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\yassine\anaconda3\lib\site-packages (from requests->tmdbv3api) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yassine\anaconda3\lib\site-packages (from requests->tmdbv3api) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yassine\anaconda3\lib\site-packages (from requests->tmdbv3api) (3.4)

In [17]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = 'd766fa2d012d94a998f49d4dbbae0a1f'

In [18]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    movie_id = result[0].id
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
    data_json = response.json()
    if data_json['genres']:
        genre_str = " " 
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name'])
        return genre_str.join(genres)
    else:
        np.NaN

In [19]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [20]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.,genres
0,J A N U A R Y,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2],NaN,Horror Mystery Thriller
1,J A N U A R Y,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3],NaN,Thriller Drama
2,J A N U A R Y,5,Stratton,Momentum Pictures / GFM Films,"Simon West (director); Duncan Falconer, Warren...",[4],NaN,Action Thriller
3,J A N U A R Y,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5],NaN,Western Crime Thriller Drama
4,J A N U A R Y,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6],NaN,Action Thriller Mystery
...,...,...,...,...,...,...,...,...
270,D E C E M B E R,25,Holmes & Watson,Columbia Pictures / Gary Sanchez Productions,Etan Cohen (director/screenplay); Will Ferrell...,NaN,[164],Mystery Adventure Comedy Crime
271,D E C E M B E R,25,Vice,Annapurna Pictures / Plan B Entertainment,Adam McKay (director/screenplay); Christian Ba...,NaN,[137],Thriller Science Fiction Action Adventure
272,D E C E M B E R,25,On the Basis of Sex,Focus Features,Mimi Leder (director); Daniel Stiepleman (scre...,NaN,[230],Drama History
273,D E C E M B E R,25,Destroyer,Annapurna Pictures,"Karyn Kusama (director); Phil Hay, Matt Manfre...",NaN,[263],Thriller Crime Drama Action
274,D E C E M B E R,28,Black Mirror: Bandersnatch,Netflix,David Slade (director); Charlie Brooker (scree...,NaN,[264],Science Fiction Mystery Drama Thriller TV Movie

In [21]:
df_2018 = df[['Title','Cast and crew','genres']]

In [22]:
df_2018

,Title,Cast and crew,genres
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller
1,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama
2,Stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller
3,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Western Crime Thriller Drama
4,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller Mystery
...,...,...,...
270,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Mystery Adventure Comedy Crime
271,Vice,Adam McKay (director/screenplay); Christian Ba...,Thriller Science Fiction Action Adventure
272,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama History
273,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Thriller Crime Drama Action
274,Black Mirror: Bandersnatch,David Slade (director); Charlie Brooker (scree...,Science Fiction Mystery Drama Thriller TV Movie

In [23]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [24]:
df_2018['director_name'] = df_2018['Cast and crew'].map(lambda x: get_director(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\930721595.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['director_name'] = df_2018['Cast and crew'].map(lambda x: get_director(x))

In [25]:
df_2018

,Title,Cast and crew,genres,director_name
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller,Adam Robitel
1,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama,Lauren Wolkstein
2,Stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller,Simon West
3,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Western Crime Thriller Drama,Warwick Thornton
4,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller Mystery,Jaume Collet-Serra
...,...,...,...,...
270,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Mystery Adventure Comedy Crime,Etan Cohen
271,Vice,Adam McKay (director/screenplay); Christian Ba...,Thriller Science Fiction Action Adventure,Adam McKay
272,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama History,Mimi Leder
273,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Thriller Crime Drama Action,Karyn Kusama
274,Black Mirror: Bandersnatch,David Slade (director); Charlie Brooker (scree...,Science Fiction Mystery Drama Thriller TV Movie,David Slade

In [26]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [27]:
df_2018['actor_1_name'] = df_2018['Cast and crew'].map(lambda x: get_actor1(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\2274966287.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['actor_1_name'] = df_2018['Cast and crew'].map(lambda x: get_actor1(x))

In [28]:
df_2018

,Title,Cast and crew,genres,director_name,actor_1_name
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller,Adam Robitel,Lin Shaye
1,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama,Lauren Wolkstein,Alex Pettyfer
2,Stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller,Simon West,Dominic Cooper
3,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Western Crime Thriller Drama,Warwick Thornton,Bryan Brown
4,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller Mystery,Jaume Collet-Serra,Liam Neeson
...,...,...,...,...,...
270,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Mystery Adventure Comedy Crime,Etan Cohen,Will Ferrell
271,Vice,Adam McKay (director/screenplay); Christian Ba...,Thriller Science Fiction Action Adventure,Adam McKay,Christian Bale
272,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama History,Mimi Leder,Felicity Jones
273,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Thriller Crime Drama Action,Karyn Kusama,Nicole Kidman
274,Black Mirror: Bandersnatch,David Slade (director); Charlie Brooker (scree...,Science Fiction Mystery Drama Thriller TV Movie,David Slade,Fionn Whitehead

In [29]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [30]:
df_2018['actor_2_name'] = df_2018['Cast and crew'].map(lambda x: get_actor2(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\3672495884.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['actor_2_name'] = df_2018['Cast and crew'].map(lambda x: get_actor2(x))

In [31]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [32]:
df_2018['actor_3_name'] = df_2018['Cast and crew'].map(lambda x: get_actor3(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\2517195254.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2018['actor_3_name'] = df_2018['Cast and crew'].map(lambda x: get_actor3(x))

In [33]:
df_2018

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell
1,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus
2,Stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan
3,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Western Crime Thriller Drama,Warwick Thornton,Bryan Brown,Sam Neill,NaN
4,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller Mystery,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson
...,...,...,...,...,...,...,...
270,Holmes & Watson,Etan Cohen (director/screenplay); Will Ferrell...,Mystery Adventure Comedy Crime,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall
271,Vice,Adam McKay (director/screenplay); Christian Ba...,Thriller Science Fiction Action Adventure,Adam McKay,Christian Bale,Amy Adams,Steve Carell
272,On the Basis of Sex,Mimi Leder (director); Daniel Stiepleman (scre...,Drama History,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux
273,Destroyer,"Karyn Kusama (director); Phil Hay, Matt Manfre...",Thriller Crime Drama Action,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell
274,Black Mirror: Bandersnatch,David Slade (director); Charlie Brooker (scree...,Science Fiction Mystery Drama Thriller TV Movie,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry

In [34]:
df_2018 = df_2018.rename(columns={'Title':'movie_title'})

In [35]:
new_df18 = df_2018.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [36]:
new_df18

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Mystery Thriller,Insidious: The Last Key
1,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Thriller Drama,The Strange Ones
2,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Action Thriller,Stratton
3,Warwick Thornton,Bryan Brown,Sam Neill,NaN,Western Crime Thriller Drama,Sweet Country
4,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Thriller Mystery,The Commuter
...,...,...,...,...,...,...
270,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,Mystery Adventure Comedy Crime,Holmes & Watson
271,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Thriller Science Fiction Action Adventure,Vice
272,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Drama History,On the Basis of Sex
273,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell,Thriller Crime Drama Action,Destroyer
274,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry,Science Fiction Mystery Drama Thriller TV Movie,Black Mirror: Bandersnatch

In [37]:
new_df18['actor_2_name'] = new_df18['actor_2_name'].replace(np.nan, 'unknown')
new_df18['actor_3_name'] = new_df18['actor_3_name'].replace(np.nan, 'unknown')

In [38]:
new_df18['movie_title'] = new_df18['movie_title'].str.lower()

In [39]:
new_df18['comb'] = new_df18['actor_1_name'] + ' ' + new_df18['actor_2_name'] + ' '+ new_df18['actor_3_name'] + ' '+ new_df18['director_name'] +' ' + new_df18['genres']

In [40]:
new_df18

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Mystery Thriller,insidious: the last key,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Thriller Drama,the strange ones,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Action Thriller,stratton,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,Warwick Thornton,Bryan Brown,Sam Neill,unknown,Western Crime Thriller Drama,sweet country,Bryan Brown Sam Neill unknown Warwick Thornton...
4,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Thriller Mystery,the commuter,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
...,...,...,...,...,...,...,...
270,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,Mystery Adventure Comedy Crime,holmes & watson,Will Ferrell John C. Reilly Rebecca Hall Etan ...
271,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Thriller Science Fiction Action Adventure,vice,Christian Bale Amy Adams Steve Carell Adam McK...
272,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Drama History,on the basis of sex,Felicity Jones Armie Hammer Justin Theroux Mim...
273,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell,Thriller Crime Drama Action,destroyer,Nicole Kidman Sebastian Stan Toby Kebbell Kary...
274,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry,Science Fiction Mystery Drama Thriller TV Movie,black mirror: bandersnatch,Fionn Whitehead Will Poulter Asim Chaudhry Dav...

## Extracting features of 2019 movies from Wikipedia

In [41]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [42]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1752420719.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [43]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,J A N U A R Y,4,Escape Room,Columbia Pictures / Original Film,"Adam Robitel (director); Bragi F. Schut, Maria...",[2]
1,J A N U A R Y,4,Rust Creek,IFC Films / Lunacy Productions,Jen McGowan (director); Julie Lipson (screenpl...,[3]
2,J A N U A R Y,4,American Hangman,Hangman Justice Productions,Wilson Coneybeare (director/screenplay); Donal...,[4]
3,J A N U A R Y,11,A Dog's Way Home,Columbia Pictures,Charles Martin Smith (director); W. Bruce Came...,[5]
4,J A N U A R Y,11,The Upside,STX Entertainment,Neil Burger (director); Jon Hartmere (screenpl...,[6]
...,...,...,...,...,...,...
240,D E C E M B E R,25,Spies in Disguise,20th Century Fox / Blue Sky Studios / Chernin ...,"Nick Bruno, Troy Quane (directors); Brad Copel...",[132]
241,D E C E M B E R,25,Little Women,Columbia Pictures / Regency Enterprises,Greta Gerwig (director/screenplay); Saoirse Ro...,[224]
242,D E C E M B E R,25,1917,Universal Pictures / DreamWorks Pictures,Sam Mendes (director/screenplay); Krysty Wilso...,[225]
243,D E C E M B E R,25,Just Mercy,Warner Bros. Pictures / Participant Media,"Destin Daniel Cretton (director/screenplay), A...",[226]
244,D E C E M B E R,27,Clemency,Neon,Chinonye Chukwu (director/screenplay); Alfre W...,[227]

In [44]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [45]:
df_2019 = df[['Title','Cast and crew','genres']]

In [46]:
df_2019

,Title,Cast and crew,genres
0,Escape Room,"Adam Robitel (director); Bragi F. Schut, Maria...",Horror Thriller Mystery
1,Rust Creek,Jen McGowan (director); Julie Lipson (screenpl...,Thriller Drama Action Crime
2,American Hangman,Wilson Coneybeare (director/screenplay); Donal...,Thriller
3,A Dog's Way Home,Charles Martin Smith (director); W. Bruce Came...,Drama Adventure Family
4,The Upside,Neil Burger (director); Jon Hartmere (screenpl...,Comedy Drama
...,...,...,...
240,Spies in Disguise,"Nick Bruno, Troy Quane (directors); Brad Copel...",Animation Action Adventure Comedy Family
241,Little Women,Greta Gerwig (director/screenplay); Saoirse Ro...,Drama Romance History
242,1917,Sam Mendes (director/screenplay); Krysty Wilso...,War Drama History
243,Just Mercy,"Destin Daniel Cretton (director/screenplay), A...",Drama Crime History
244,Clemency,Chinonye Chukwu (director/screenplay); Alfre W...,Drama

In [47]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [48]:
df_2019['director_name'] = df_2019['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\203239715.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['director_name'] = df_2019['Cast and crew'].map(lambda x: get_director(str(x)))

In [49]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [50]:
df_2019['actor_1_name'] = df_2019['Cast and crew'].map(lambda x: get_actor1(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1562076556.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['actor_1_name'] = df_2019['Cast and crew'].map(lambda x: get_actor1(x))

In [51]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [52]:
df_2019['actor_2_name'] = df_2019['Cast and crew'].map(lambda x: get_actor2(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\3736213850.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2019['actor_2_name'] = df_2019['Cast and crew'].map(lambda x: get_actor2(x))

In [53]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [54]:
df_2019['actor_3_name'] = df_2019['Cast and crew'].map(lambda x: get_actor3(x))

In [55]:
df_2019 = df_2019.rename(columns={'Title':'movie_title'})

In [56]:
new_df19 = df_2019.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [57]:
new_df19['actor_2_name'] = new_df19['actor_2_name'].replace(np.nan, 'unknown')
new_df19['actor_3_name'] = new_df19['actor_3_name'].replace(np.nan, 'unknown')

In [58]:
new_df19['movie_title'] = new_df19['movie_title'].str.lower()

In [59]:
new_df19['comb'] = new_df19['actor_1_name'] + ' ' + new_df19['actor_2_name'] + ' '+ new_df19['actor_3_name'] + ' '+ new_df19['director_name'] +' ' + new_df19['genres']

In [60]:
new_df19

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Taylor Russell,Logan Miller,Deborah Ann Woll,Horror Thriller Mystery,escape room,Taylor Russell Logan Miller Deborah Ann Woll A...
1,Jen McGowan,Hermione Corfield,Jay Paulson,Sean O'Bryan,Thriller Drama Action Crime,rust creek,Hermione Corfield Jay Paulson Sean O'Bryan Jen...
2,Wilson Coneybeare,Donald Sutherland,Vincent Kartheiser,Oliver Dennis,Thriller,american hangman,Donald Sutherland Vincent Kartheiser Oliver De...
3,Charles Martin Smith,Bryce Dallas Howard,Edward James Olmos,Alexandra Shipp,Drama Adventure Family,a dog's way home,Bryce Dallas Howard Edward James Olmos Alexand...
4,Neil Burger,Bryan Cranston,Kevin Hart,Nicole Kidman,Comedy Drama,the upside,Bryan Cranston Kevin Hart Nicole Kidman Neil B...
...,...,...,...,...,...,...,...
240,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,Will Smith Tom Holland Rashida Jones Nick Brun...
241,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance History,little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
242,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama History,1917,George MacKay Dean-Charles Chapman Mark Strong...
243,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
244,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

In [62]:
my_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Mystery Thriller,insidious: the last key,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Thriller Drama,the strange ones,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Action Thriller,stratton,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,Warwick Thornton,Bryan Brown,Sam Neill,unknown,Western Crime Thriller Drama,sweet country,Bryan Brown Sam Neill unknown Warwick Thornton...
4,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Thriller Mystery,the commuter,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
...,...,...,...,...,...,...,...
515,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,Will Smith Tom Holland Rashida Jones Nick Brun...
516,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance History,little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
517,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama History,1917,George MacKay Dean-Charles Chapman Mark Strong...
518,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
519,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

In [63]:
old_df = pd.read_csv('new_data.csv')

In [64]:
old_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
5359,Jim Strouse,Jessica Williams,Chris O'Dowd,Keith Stanfield,Romance Comedy,the incredible jessica james,Jessica Williams Chris O'Dowd Keith Stanfield ...
5360,Farhad Mann,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Romance,can't buy my love,Adelaide Kane Benjamin Hollingsworth Jean Loui...
5361,Hannaleena Hauru,Inka HaapamÃ¤ki,Rosa Honkonen,Tiitus Rantala,Romance Comedy,thick lashes of lauri mÃ¤ntyvaara,Inka HaapamÃ¤ki Rosa Honkonen Tiitus Rantala Ha...
5362,Jonathan A. Rosenbaum,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Crime Comedy Action Family,cop and a half: new recruit,Lou Diamond Phillips Wallace Shawn Gina Holden...
5363,Ravi Udyawar,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Crime Drama Thriller,mom,Sridevi Kapoor Sajal Ali Akshaye Khanna Ravi U...

In [65]:
final_df = old_df.append(my_df,ignore_index=True)

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\2046453413.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = old_df.append(my_df,ignore_index=True)

In [66]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
5879,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,Will Smith Tom Holland Rashida Jones Nick Brun...
5880,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance History,little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
5881,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama History,1917,George MacKay Dean-Charles Chapman Mark Strong...
5882,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
5883,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

In [67]:
final_df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [68]:
final_df = final_df.dropna(how='any')

In [69]:
final_df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [72]:
final_df.to_csv('final_data.csv',index=False)

## Extracting features of 2020 movies from Wikipedia

In [73]:
link3 = "https://en.wikipedia.org/wiki/List_of_American_films_of_2020"

In [74]:
df1 = pd.read_html(link3, header=0)[2]
df2 = pd.read_html(link3, header=0)[3]
df3 = pd.read_html(link3, header=0)[4]
df4 = pd.read_html(link3, header=0)[5]

In [75]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1752420719.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [76]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.
0,J A N U A R Y,3,The Grudge,Screen Gems / Stage 6 Films / Ghost House Pict...,Nicolas Pesce (director/screenplay); Andrea Ri...,[2],NaN
1,J A N U A R Y,10,Underwater,20th Century Fox / TSG Entertainment / Chernin...,"William Eubank (director); Brian Duffield, Ada...",[3],NaN
2,J A N U A R Y,10,Like a Boss,Paramount Pictures / Artists First,"Miguel Arteta (director); Sam Pitman, Adam Col...",[4],NaN
3,J A N U A R Y,10,Three Christs,IFC Films,Jon Avnet (director/screenplay); Eric Nazarian...,NaN,NaN
4,J A N U A R Y,10,Inherit the Viper,Barry Films / Tycor International Film Company,Anthony Jerjen (director); Andrew Crabtree (sc...,[5],NaN
...,...,...,...,...,...,...,...
270,D E C E M B E R,25,We Can Be Heroes,Netflix / Troublemaker Studios / Double R Prod...,Robert Rodriguez (director/screenplay); Priyan...,NaN,[241]
271,D E C E M B E R,25,News of the World,Universal Pictures / Perfect World Pictures,Paul Greengrass (director/screenplay); Luke Da...,NaN,[242]
272,D E C E M B E R,25,One Night in Miami...,Amazon Studios,Regina King (director); Kemp Powers (screenpla...,NaN,[243]
273,D E C E M B E R,25,Promising Young Woman,Focus Features / FilmNation Entertainment,Emerald Fennell (director/screenplay); Carey M...,NaN,[244]
274,D E C E M B E R,30,Pieces of a Woman,Netflix / Bron Studios,KornÃ©l MundruczÃ³ (director); Kata WÃ©ber (scree...,NaN,[245]

In [77]:
df_2020 = df[['Title','Cast and crew']]

In [78]:
df_2020

                     Title                                      Cast and crew
0               The Grudge  Nicolas Pesce (director/screenplay); Andrea Ri...
1               Underwater  William Eubank (director); Brian Duffield, Ada...
2              Like a Boss  Miguel Arteta (director); Sam Pitman, Adam Col...
3            Three Christs  Jon Avnet (director/screenplay); Eric Nazarian...
4        Inherit the Viper  Anthony Jerjen (director); Andrew Crabtree (sc...
..                     ...                                                ...
270       We Can Be Heroes  Robert Rodriguez (director/screenplay); Priyan...
271      News of the World  Paul Greengrass (director/screenplay); Luke Da...
272  One Night in Miami...  Regina King (director); Kemp Powers (screenpla...
273  Promising Young Woman  Emerald Fennell (director/screenplay); Carey M...
274      Pieces of a Woman  KornÃ©l MundruczÃ³ (director); Kata WÃ©ber (scree...

[275 rows x 2 columns]

In [79]:
def get_genre1(x):
    genres = []
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['genres']:
          genre_str = " " 
          for i in range(0,len(data_json['genres'])):
              genres.append(data_json['genres'][i]['name'])
          return genre_str.join(genres)
      else:
          return np.NaN

In [80]:
df_2020['genres'] = df_2020['Title'].map(lambda x: get_genre1(str(x)))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\2499978658.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['genres'] = df_2020['Title'].map(lambda x: get_genre1(str(x)))

In [81]:
df_2020

,Title,Cast and crew,genres
0,The Grudge,Nicolas Pesce (director/screenplay); Andrea Ri...,Horror Mystery
1,Underwater,"William Eubank (director); Brian Duffield, Ada...",Horror Science Fiction Action Adventure
2,Like a Boss,"Miguel Arteta (director); Sam Pitman, Adam Col...",Comedy
3,Three Christs,Jon Avnet (director/screenplay); Eric Nazarian...,Drama
4,Inherit the Viper,Anthony Jerjen (director); Andrew Crabtree (sc...,Crime Thriller Drama
...,...,...,...
270,We Can Be Heroes,Robert Rodriguez (director/screenplay); Priyan...,Family Action Fantasy Comedy
271,News of the World,Paul Greengrass (director/screenplay); Luke Da...,Drama Western Adventure Action
272,One Night in Miami...,Regina King (director); Kemp Powers (screenpla...,Drama
273,Promising Young Woman,Emerald Fennell (director/screenplay); Carey M...,Thriller Crime Drama
274,Pieces of a Woman,KornÃ©l MundruczÃ³ (director); Kata WÃ©ber (scree...,Drama

In [82]:
df_2020['director_name'] = df_2020['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\3962101783.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['director_name'] = df_2020['Cast and crew'].map(lambda x: get_director(str(x)))

In [83]:
df_2020['actor_1_name'] = df_2020['Cast and crew'].map(lambda x: get_actor1(str(x)))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1815024756.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['actor_1_name'] = df_2020['Cast and crew'].map(lambda x: get_actor1(str(x)))

In [84]:
df_2020['actor_2_name'] = df_2020['Cast and crew'].map(lambda x: get_actor2(str(x)))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\3667490226.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020['actor_2_name'] = df_2020['Cast and crew'].map(lambda x: get_actor2(str(x)))

In [85]:
df_2020['actor_3_name'] = df_2020['Cast and crew'].map(lambda x: get_actor3(str(x)))

In [86]:
df_2020

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,The Grudge,Nicolas Pesce (director/screenplay); Andrea Ri...,Horror Mystery,Nicolas Pesce,Andrea Riseborough,DemiÃ¡n Bichir,John Cho
1,Underwater,"William Eubank (director); Brian Duffield, Ada...",Horror Science Fiction Action Adventure,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick
2,Like a Boss,"Miguel Arteta (director); Sam Pitman, Adam Col...",Comedy,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek
3,Three Christs,Jon Avnet (director/screenplay); Eric Nazarian...,Drama,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins
4,Inherit the Viper,Anthony Jerjen (director); Andrew Crabtree (sc...,Crime Thriller Drama,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs
...,...,...,...,...,...,...,...
270,We Can Be Heroes,Robert Rodriguez (director/screenplay); Priyan...,Family Action Fantasy Comedy,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin
271,News of the World,Paul Greengrass (director/screenplay); Luke Da...,Drama Western Adventure Action,Paul Greengrass,Tom Hanks,Helena Zengel,NaN
272,One Night in Miami...,Regina King (director); Kemp Powers (screenpla...,Drama,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge
273,Promising Young Woman,Emerald Fennell (director/screenplay); Carey M...,Thriller Crime Drama,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie
274,Pieces of a Woman,KornÃ©l MundruczÃ³ (director); Kata WÃ©ber (scree...,Drama,KornÃ©l MundruczÃ³,Vanessa Kirby,Shia LaBeouf,Molly Parker

In [87]:
df_2020 = df_2020.rename(columns={'Title':'movie_title'})

In [88]:
new_df20 = df_2020.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [89]:
new_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Nicolas Pesce,Andrea Riseborough,DemiÃ¡n Bichir,John Cho,Horror Mystery,The Grudge
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,Horror Science Fiction Action Adventure,Underwater
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Comedy,Like a Boss
3,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins,Drama,Three Christs
4,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,Crime Thriller Drama,Inherit the Viper
...,...,...,...,...,...,...
270,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Family Action Fantasy Comedy,We Can Be Heroes
271,Paul Greengrass,Tom Hanks,Helena Zengel,NaN,Drama Western Adventure Action,News of the World
272,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,One Night in Miami...
273,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Thriller Crime Drama,Promising Young Woman
274,KornÃ©l MundruczÃ³,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,Pieces of a Woman

In [90]:
new_df20['comb'] = new_df20['actor_1_name'] + ' ' + new_df20['actor_2_name'] + ' '+ new_df20['actor_3_name'] + ' '+ new_df20['director_name'] +' ' + new_df20['genres']

In [91]:
new_df20.isna().sum()

director_name     0
actor_1_name      0
actor_2_name      5
actor_3_name     28
genres            2
movie_title       0
comb             29
dtype: int64

In [92]:
new_df20 = new_df20.dropna(how='any')

In [93]:
new_df20.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [94]:
new_df20['movie_title'] = new_df20['movie_title'].str.lower()

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\117998293.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df20['movie_title'] = new_df20['movie_title'].str.lower()

In [95]:
new_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Nicolas Pesce,Andrea Riseborough,DemiÃ¡n Bichir,John Cho,Horror Mystery,the grudge,Andrea Riseborough DemiÃ¡n Bichir John Cho Nico...
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,Horror Science Fiction Action Adventure,underwater,Kristen Stewart Vincent Cassel Jessica Henwick...
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Comedy,like a boss,Tiffany Haddish Rose Byrne Salma Hayek Miguel ...
3,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins,Drama,three christs,Richard Gere Peter Dinklage Walton Goggins Jon...
4,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,Crime Thriller Drama,inherit the viper,Josh Hartnett Margarita Levieva Chandler Riggs...
...,...,...,...,...,...,...,...
269,Pete Docter,Jamie Foxx,Tina Fey,Graham Norton,Animation Family Comedy Fantasy Drama,soul,Jamie Foxx Tina Fey Graham Norton Pete Docter ...
270,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Family Action Fantasy Comedy,we can be heroes,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...
272,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,one night in miami...,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
273,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Thriller Crime Drama,promising young woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
274,KornÃ©l MundruczÃ³,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,pieces of a woman,Vanessa Kirby Shia LaBeouf Molly Parker KornÃ©l...

In [96]:
old_df = pd.read_csv('final_data.csv')

In [97]:
old_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
5879,"Nick Bruno, Troy Quane",Will Smith,Tom Holland,Rashida Jones,Animation Action Adventure Comedy Family,spies in disguise,Will Smith Tom Holland Rashida Jones Nick Brun...
5880,Greta Gerwig,Saoirse Ronan,Emma Watson,Florence Pugh,Drama Romance History,little women,Saoirse Ronan Emma Watson Florence Pugh Greta ...
5881,Sam Mendes,George MacKay,Dean-Charles Chapman,Mark Strong,War Drama History,1917,George MacKay Dean-Charles Chapman Mark Strong...
5882,Destin Daniel Cretton,Michael B. Jordan,Jamie Foxx,Brie Larson,Drama Crime History,just mercy,Michael B. Jordan Jamie Foxx Brie Larson Desti...
5883,Chinonye Chukwu,Alfre Woodard,Wendell Pierce,Aldis Hodge,Drama,clemency,Alfre Woodard Wendell Pierce Aldis Hodge Chino...

In [98]:
final_df = old_df.append(new_df20,ignore_index=True)

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1526179653.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = old_df.append(new_df20,ignore_index=True)

In [99]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
6125,Pete Docter,Jamie Foxx,Tina Fey,Graham Norton,Animation Family Comedy Fantasy Drama,soul,Jamie Foxx Tina Fey Graham Norton Pete Docter ...
6126,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Family Action Fantasy Comedy,we can be heroes,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...
6127,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,one night in miami...,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
6128,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Thriller Crime Drama,promising young woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
6129,KornÃ©l MundruczÃ³,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,pieces of a woman,Vanessa Kirby Shia LaBeouf Molly Parker KornÃ©l...

In [100]:
final_df.to_csv('main_data.csv',index=False)

## Extracting features of 2021 movies from Wikipedia

In [101]:
link4 = "https://en.wikipedia.org/wiki/List_of_American_films_of_2021"

In [102]:
df1 = pd.read_html(link4, header=0)[2]
df2 = pd.read_html(link4, header=0)[3]
df3 = pd.read_html(link4, header=0)[4]
df4 = pd.read_html(link4, header=0)[5]

In [103]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1752420719.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [104]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.
0,J A N U A R Y,1.0,Shadow in the Cloud,Vertical Entertainment,Roseanne Liang (director/screenplay); Max Land...,[2],NaN
1,J A N U A R Y,13.0,The White Tiger,Netflix / Noruz Films,Ramin Bahrani (director/screenplay); Adarsh Go...,NaN,NaN
2,J A N U A R Y,14.0,Locked Down,HBO Max / Warner Bros. Pictures,Doug Liman (director); Steven Knight (screenpl...,[3],NaN
3,J A N U A R Y,15.0,The Dig,Netflix / Clerkenwell Films,Simon Stone (director); Moira Buffini (screenp...,[4],NaN
4,J A N U A R Y,15.0,Outside the Wire,Netflix,"Mikael HÃ¥fstrÃ¶m (director); Rob Yescombe, Rowa...",[5],NaN
...,...,...,...,...,...,...,...
356,D E C E M B E R,25.0,The Tragedy of Macbeth,Apple TV+ / A24 / IAC Films,Joel Coen (director/screenplay); Denzel Washin...,NaN,[273]
357,D E C E M B E R,25.0,A Journal for Jordan,Columbia Pictures / Escape Artists / Bron Studios,Denzel Washington (director); Virgil Williams ...,NaN,[274]
358,D E C E M B E R,25.0,American Underdog,Lionsgate,"Erwin brothers (directors); Jon Erwin, David A...",NaN,[275]
359,D E C E M B E R,26.0,Memoria,Neon,Apichatpong Weerasethakul (director/acreenplay...,NaN,[276]
360,D E C E M B E R,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
df['genres'] = df['Title'].map(lambda x: get_genre1(str(x)))

In [106]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.,genres
0,J A N U A R Y,1.0,Shadow in the Cloud,Vertical Entertainment,Roseanne Liang (director/screenplay); Max Land...,[2],NaN,Horror Action War
1,J A N U A R Y,13.0,The White Tiger,Netflix / Noruz Films,Ramin Bahrani (director/screenplay); Adarsh Go...,NaN,NaN,Drama
2,J A N U A R Y,14.0,Locked Down,HBO Max / Warner Bros. Pictures,Doug Liman (director); Steven Knight (screenpl...,[3],NaN,Comedy Crime Drama
3,J A N U A R Y,15.0,The Dig,Netflix / Clerkenwell Films,Simon Stone (director); Moira Buffini (screenp...,[4],NaN,Drama History
4,J A N U A R Y,15.0,Outside the Wire,Netflix,"Mikael HÃ¥fstrÃ¶m (director); Rob Yescombe, Rowa...",[5],NaN,Thriller Action Science Fiction
...,...,...,...,...,...,...,...,...
356,D E C E M B E R,25.0,The Tragedy of Macbeth,Apple TV+ / A24 / IAC Films,Joel Coen (director/screenplay); Denzel Washin...,NaN,[273],Drama War
357,D E C E M B E R,25.0,A Journal for Jordan,Columbia Pictures / Escape Artists / Bron Studios,Denzel Washington (director); Virgil Williams ...,NaN,[274],Drama Romance
358,D E C E M B E R,25.0,American Underdog,Lionsgate,"Erwin brothers (directors); Jon Erwin, David A...",NaN,[275],Drama
359,D E C E M B E R,26.0,Memoria,Neon,Apichatpong Weerasethakul (director/acreenplay...,NaN,[276],Drama
360,D E C E M B E R,NaN,NaN,NaN,NaN,NaN,NaN,Drama

In [107]:
df_2021 = df[['Title','Cast and crew','genres']]

In [108]:
df_2021

,Title,Cast and crew,genres
0,Shadow in the Cloud,Roseanne Liang (director/screenplay); Max Land...,Horror Action War
1,The White Tiger,Ramin Bahrani (director/screenplay); Adarsh Go...,Drama
2,Locked Down,Doug Liman (director); Steven Knight (screenpl...,Comedy Crime Drama
3,The Dig,Simon Stone (director); Moira Buffini (screenp...,Drama History
4,Outside the Wire,"Mikael HÃ¥fstrÃ¶m (director); Rob Yescombe, Rowa...",Thriller Action Science Fiction
...,...,...,...
356,The Tragedy of Macbeth,Joel Coen (director/screenplay); Denzel Washin...,Drama War
357,A Journal for Jordan,Denzel Washington (director); Virgil Williams ...,Drama Romance
358,American Underdog,"Erwin brothers (directors); Jon Erwin, David A...",Drama
359,Memoria,Apichatpong Weerasethakul (director/acreenplay...,Drama
360,NaN,NaN,Drama

In [109]:
def get_director1(x):
    if pd.isna(x):
        return None
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [110]:
df_2021['director_name'] = df_2021['Cast and crew'].map(lambda x: get_director1(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\2981887549.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['director_name'] = df_2021['Cast and crew'].map(lambda x: get_director1(x))

In [111]:
def get_actor1_1(x):
    if pd.isna(x):
        return None
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [112]:
def get_actor2_2(x):
    if pd.isna(x):
        return np.NaN
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [113]:
def get_actor3_3(x):
    if pd.isna(x):
        return np.NaN    
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [114]:
df_2021['actor_1_name'] = df_2021['Cast and crew'].map(lambda x: get_actor1_1(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1102623037.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['actor_1_name'] = df_2021['Cast and crew'].map(lambda x: get_actor1_1(x))

In [115]:
df_2021['actor_2_name'] = df_2021['Cast and crew'].map(lambda x: get_actor2_2(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1675635709.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['actor_2_name'] = df_2021['Cast and crew'].map(lambda x: get_actor2_2(x))

In [116]:
df_2021['actor_3_name'] = df_2021['Cast and crew'].map(lambda x: get_actor3_3(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\3148803455.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['actor_3_name'] = df_2021['Cast and crew'].map(lambda x: get_actor3_3(x))

In [117]:
df_2021

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Shadow in the Cloud,Roseanne Liang (director/screenplay); Max Land...,Horror Action War,Roseanne Liang,ChloÃ« Grace Moretz,Taylor John Smith,Beulah Koale
1,The White Tiger,Ramin Bahrani (director/screenplay); Adarsh Go...,Drama,Ramin Bahrani,Adarsh Gourav,Rajkummar Rao,Priyanka Chopra Jonas
2,Locked Down,Doug Liman (director); Steven Knight (screenpl...,Comedy Crime Drama,Doug Liman,Anne Hathaway,Chiwetel Ejiofor,Stephen Merchant
3,The Dig,Simon Stone (director); Moira Buffini (screenp...,Drama History,Simon Stone,Carey Mulligan,Ralph Fiennes,Lily James
4,Outside the Wire,"Mikael HÃ¥fstrÃ¶m (director); Rob Yescombe, Rowa...",Thriller Action Science Fiction,Mikael HÃ¥fstrÃ¶m,Anthony Mackie,Damson Idris,Emily Beecham
...,...,...,...,...,...,...,...
356,The Tragedy of Macbeth,Joel Coen (director/screenplay); Denzel Washin...,Drama War,Joel Coen,Denzel Washington,Frances McDormand,Bertie Carvel
357,A Journal for Jordan,Denzel Washington (director); Virgil Williams ...,Drama Romance,Denzel Washington,Michael B. Jordan,ChantÃ© Adams,Jalon Christian
358,American Underdog,"Erwin brothers (directors); Jon Erwin, David A...",Drama,Erwin brothers,Zachary Levi,Anna Paquin,Dennis Quaid
359,Memoria,Apichatpong Weerasethakul (director/acreenplay...,Drama,Apichatpong Weerasethakul (director/acreenplay...,Apichatpong Weerasethakul (director/acreenplay...,Elkin DÃ­az,Jeanne Balibar
360,NaN,NaN,Drama,None,None,NaN,NaN

In [118]:
df_2021 = df_2021.rename(columns={'Title':'movie_title'})

In [119]:
new_df21 = df_2021.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [120]:
new_df21

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Roseanne Liang,ChloÃ« Grace Moretz,Taylor John Smith,Beulah Koale,Horror Action War,Shadow in the Cloud
1,Ramin Bahrani,Adarsh Gourav,Rajkummar Rao,Priyanka Chopra Jonas,Drama,The White Tiger
2,Doug Liman,Anne Hathaway,Chiwetel Ejiofor,Stephen Merchant,Comedy Crime Drama,Locked Down
3,Simon Stone,Carey Mulligan,Ralph Fiennes,Lily James,Drama History,The Dig
4,Mikael HÃ¥fstrÃ¶m,Anthony Mackie,Damson Idris,Emily Beecham,Thriller Action Science Fiction,Outside the Wire
...,...,...,...,...,...,...
356,Joel Coen,Denzel Washington,Frances McDormand,Bertie Carvel,Drama War,The Tragedy of Macbeth
357,Denzel Washington,Michael B. Jordan,ChantÃ© Adams,Jalon Christian,Drama Romance,A Journal for Jordan
358,Erwin brothers,Zachary Levi,Anna Paquin,Dennis Quaid,Drama,American Underdog
359,Apichatpong Weerasethakul (director/acreenplay...,Apichatpong Weerasethakul (director/acreenplay...,Elkin DÃ­az,Jeanne Balibar,Drama,Memoria
360,None,None,NaN,NaN,Drama,NaN

In [121]:
new_df21['actor_2_name'] = new_df21['actor_2_name'].replace(np.nan, 'unknown')
new_df21['actor_3_name'] = new_df21['actor_3_name'].replace(np.nan, 'unknown')

In [122]:
new_df21['movie_title'] = new_df21['movie_title'].str.lower()

In [123]:
new_df21['comb'] = new_df21['actor_1_name'] + ' ' + new_df21['actor_2_name'] + ' '+ new_df21['actor_3_name'] + ' '+ new_df21['director_name'] +' ' + new_df21['genres']

In [238]:
new_df21

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Simon Kinberg,Jessica Chastain,Lupita Nyong'o,PenÃ©lope Cruz,Action Thriller,the 355,Jessica Chastain Lupita Nyong'o PenÃ©lope Cruz ...
1,Patricia Harris Seeley,Autumn Reeser,Antonio Cupo,Danny Trejo,Family Animation Fantasy Horror,the legend of la llorona,Autumn Reeser Antonio Cupo Danny Trejo Patrici...
2,Asif Akbar,Mickey Rourke,Michael Jai White,unknown,Action Crime Thriller,the commando,Mickey Rourke Michael Jai White unknown Asif A...
3,Edward Drake,Timothy V. Murphy,Bruce Willis,unknown,Action Adventure Thriller,american siege,Timothy V. Murphy Bruce Willis unknown Edward ...
4,"Matt Bettinelli-Olpin, Tyler Gillett",Melissa Barrera,Mason Gooding,Jenna Ortega,Horror Mystery Thriller,scream,Melissa Barrera Mason Gooding Jenna Ortega Mat...
...,...,...,...,...,...,...,...
319,Damien Chazelle,Brad Pitt,Margot Robbie,Diego Calva,Drama Comedy,babylon,Brad Pitt Margot Robbie Diego Calva Damien Cha...
320,Kasi Lemmons,Naomi Ackie,Stanley Tucci,Ashton Sanders,Music History Drama,whitney houston: i wanna dance with somebody,Naomi Ackie Stanley Tucci Ashton Sanders Kasi ...
321,Scott Cooper,Christian Bale,Harry Melling,Gillian Anderson,Crime,the pale blue eye,Christian Bale Harry Melling Gillian Anderson ...
322,Sarah Polley,Rooney Mara,Claire Foy,Jessie Buckley,Drama,women talking,Rooney Mara Claire Foy Jessie Buckley Sarah Po...
323,Marc Forster,Tom Hanks,Mariana TreviÃ±o,Rachel Keller,Comedy Drama,a man called otto,Tom Hanks Mariana TreviÃ±o Rachel Keller Marc F...

In [125]:
new_df21 = new_df21[new_df21['movie_title'] != 'memoria']

In [237]:
new_df21.drop(36, inplace=True)

KeyError: '[360] not found in axis'

In [126]:
new_df21

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Roseanne Liang,ChloÃ« Grace Moretz,Taylor John Smith,Beulah Koale,Horror Action War,shadow in the cloud,ChloÃ« Grace Moretz Taylor John Smith Beulah Ko...
1,Ramin Bahrani,Adarsh Gourav,Rajkummar Rao,Priyanka Chopra Jonas,Drama,the white tiger,Adarsh Gourav Rajkummar Rao Priyanka Chopra Jo...
2,Doug Liman,Anne Hathaway,Chiwetel Ejiofor,Stephen Merchant,Comedy Crime Drama,locked down,Anne Hathaway Chiwetel Ejiofor Stephen Merchan...
3,Simon Stone,Carey Mulligan,Ralph Fiennes,Lily James,Drama History,the dig,Carey Mulligan Ralph Fiennes Lily James Simon ...
4,Mikael HÃ¥fstrÃ¶m,Anthony Mackie,Damson Idris,Emily Beecham,Thriller Action Science Fiction,outside the wire,Anthony Mackie Damson Idris Emily Beecham Mika...
...,...,...,...,...,...,...,...
355,Matthew Vaughn,Ralph Fiennes,Gemma Arterton,Rhys Ifans,Action Adventure Thriller,the king's man,Ralph Fiennes Gemma Arterton Rhys Ifans Matthe...
356,Joel Coen,Denzel Washington,Frances McDormand,Bertie Carvel,Drama War,the tragedy of macbeth,Denzel Washington Frances McDormand Bertie Car...
357,Denzel Washington,Michael B. Jordan,ChantÃ© Adams,Jalon Christian,Drama Romance,a journal for jordan,Michael B. Jordan ChantÃ© Adams Jalon Christian...
358,Erwin brothers,Zachary Levi,Anna Paquin,Dennis Quaid,Drama,american underdog,Zachary Levi Anna Paquin Dennis Quaid Erwin br...
360,None,None,unknown,unknown,Drama,NaN,NaN

## Extracting features of 2022 movies from Wikipedia

In [181]:
link5 = "https://en.wikipedia.org/wiki/List_of_American_films_of_2022"

In [182]:
df1 = pd.read_html(link5, header=0)[2]
df2 = pd.read_html(link5, header=0)[3]
df3 = pd.read_html(link5, header=0)[4]
df4 = pd.read_html(link5, header=0)[5]

In [183]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1752420719.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [184]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.
0,J A N U A R Y,7.0,The 355,Universal Pictures / Freckle Films / FilmNatio...,Simon Kinberg (director/screenplay); Theresa R...,[2],NaN
1,J A N U A R Y,7.0,The Legend of La Llorona,Saban Films / Ageless Pictures,Patricia Harris Seeley (director/screenplay); ...,[3],NaN
2,J A N U A R Y,7.0,The Commando,Saban Films / Premiere Entertainment,Asif Akbar (director); Koji Steven Sakai (scre...,[4],NaN
3,J A N U A R Y,7.0,American Siege,Vertical Entertainment,Edward Drake (director/screenplay); Timothy V....,[5],NaN
4,J A N U A R Y,14.0,Scream,Paramount Pictures / Spyglass Media Group / Ra...,"Matt Bettinelli-Olpin, Tyler Gillett (director...",[6],NaN
...,...,...,...,...,...,...,...
324,D E C E M B E R,30.0,"Alice, Darling",Lionsgate / Elevation Pictures,Mary Nighy (director); Alanna Francis (screenp...,NaN,[261]
325,D E C E M B E R,NaN,NaN,NaN,NaN,NaN,NaN
326,D E C E M B E R,NaN,NaN,NaN,NaN,NaN,NaN
327,D E C E M B E R,NaN,NaN,NaN,NaN,NaN,NaN
328,D E C E M B E R,NaN,NaN,NaN,NaN,NaN,NaN

In [185]:
df.drop([324, 325, 326, 327,328], inplace=True)

In [186]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.
0,J A N U A R Y,7.0,The 355,Universal Pictures / Freckle Films / FilmNatio...,Simon Kinberg (director/screenplay); Theresa R...,[2],NaN
1,J A N U A R Y,7.0,The Legend of La Llorona,Saban Films / Ageless Pictures,Patricia Harris Seeley (director/screenplay); ...,[3],NaN
2,J A N U A R Y,7.0,The Commando,Saban Films / Premiere Entertainment,Asif Akbar (director); Koji Steven Sakai (scre...,[4],NaN
3,J A N U A R Y,7.0,American Siege,Vertical Entertainment,Edward Drake (director/screenplay); Timothy V....,[5],NaN
4,J A N U A R Y,14.0,Scream,Paramount Pictures / Spyglass Media Group / Ra...,"Matt Bettinelli-Olpin, Tyler Gillett (director...",[6],NaN
...,...,...,...,...,...,...,...
319,D E C E M B E R,23.0,Babylon,Paramount Pictures,Damien Chazelle (director/screenplay); Brad Pi...,NaN,[258]
320,D E C E M B E R,23.0,Whitney Houston: I Wanna Dance with Somebody,TriStar Pictures / Black Label Media,Kasi Lemmons (director); Anthony McCarten (scr...,NaN,[55]
321,D E C E M B E R,23.0,The Pale Blue Eye,Netflix / Cross Creek Pictures,Scott Cooper (director/screenplay); Christian ...,NaN,[181]
322,D E C E M B E R,23.0,Women Talking,Orion Pictures / Plan B Entertainment,Sarah Polley (director/screenplay); Rooney Mar...,NaN,[259]
323,D E C E M B E R,29.0,A Man Called Otto,Columbia Pictures / Stage 6 Films / Playtone /...,"Marc Forster (director), David Magee (screenpl...",NaN,[260]

In [187]:
df['genres'] = df['Title'].map(lambda x: get_genre1(str(x)))

In [188]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.,genres
0,J A N U A R Y,7.0,The 355,Universal Pictures / Freckle Films / FilmNatio...,Simon Kinberg (director/screenplay); Theresa R...,[2],NaN,Action Thriller
1,J A N U A R Y,7.0,The Legend of La Llorona,Saban Films / Ageless Pictures,Patricia Harris Seeley (director/screenplay); ...,[3],NaN,Family Animation Fantasy Horror
2,J A N U A R Y,7.0,The Commando,Saban Films / Premiere Entertainment,Asif Akbar (director); Koji Steven Sakai (scre...,[4],NaN,Action Crime Thriller
3,J A N U A R Y,7.0,American Siege,Vertical Entertainment,Edward Drake (director/screenplay); Timothy V....,[5],NaN,Action Adventure Thriller
4,J A N U A R Y,14.0,Scream,Paramount Pictures / Spyglass Media Group / Ra...,"Matt Bettinelli-Olpin, Tyler Gillett (director...",[6],NaN,Horror Mystery Thriller
...,...,...,...,...,...,...,...,...
319,D E C E M B E R,23.0,Babylon,Paramount Pictures,Damien Chazelle (director/screenplay); Brad Pi...,NaN,[258],Drama Comedy
320,D E C E M B E R,23.0,Whitney Houston: I Wanna Dance with Somebody,TriStar Pictures / Black Label Media,Kasi Lemmons (director); Anthony McCarten (scr...,NaN,[55],Music History Drama
321,D E C E M B E R,23.0,The Pale Blue Eye,Netflix / Cross Creek Pictures,Scott Cooper (director/screenplay); Christian ...,NaN,[181],Crime
322,D E C E M B E R,23.0,Women Talking,Orion Pictures / Plan B Entertainment,Sarah Polley (director/screenplay); Rooney Mar...,NaN,[259],Drama
323,D E C E M B E R,29.0,A Man Called Otto,Columbia Pictures / Stage 6 Films / Playtone /...,"Marc Forster (director), David Magee (screenpl...",NaN,[260],Comedy Drama

In [189]:
df_2022 = df[['Title','Cast and crew','genres']]

In [190]:
df_2022

,Title,Cast and crew,genres
0,The 355,Simon Kinberg (director/screenplay); Theresa R...,Action Thriller
1,The Legend of La Llorona,Patricia Harris Seeley (director/screenplay); ...,Family Animation Fantasy Horror
2,The Commando,Asif Akbar (director); Koji Steven Sakai (scre...,Action Crime Thriller
3,American Siege,Edward Drake (director/screenplay); Timothy V....,Action Adventure Thriller
4,Scream,"Matt Bettinelli-Olpin, Tyler Gillett (director...",Horror Mystery Thriller
...,...,...,...
319,Babylon,Damien Chazelle (director/screenplay); Brad Pi...,Drama Comedy
320,Whitney Houston: I Wanna Dance with Somebody,Kasi Lemmons (director); Anthony McCarten (scr...,Music History Drama
321,The Pale Blue Eye,Scott Cooper (director/screenplay); Christian ...,Crime
322,Women Talking,Sarah Polley (director/screenplay); Rooney Mar...,Drama
323,A Man Called Otto,"Marc Forster (director), David Magee (screenpl...",Comedy Drama

In [191]:
df_2022['director_name'] = df_2022['Cast and crew'].map(lambda x: get_director(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1906082619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['director_name'] = df_2022['Cast and crew'].map(lambda x: get_director(x))

In [192]:
df_2022

,Title,Cast and crew,genres,director_name
0,The 355,Simon Kinberg (director/screenplay); Theresa R...,Action Thriller,Simon Kinberg
1,The Legend of La Llorona,Patricia Harris Seeley (director/screenplay); ...,Family Animation Fantasy Horror,Patricia Harris Seeley
2,The Commando,Asif Akbar (director); Koji Steven Sakai (scre...,Action Crime Thriller,Asif Akbar
3,American Siege,Edward Drake (director/screenplay); Timothy V....,Action Adventure Thriller,Edward Drake
4,Scream,"Matt Bettinelli-Olpin, Tyler Gillett (director...",Horror Mystery Thriller,"Matt Bettinelli-Olpin, Tyler Gillett"
...,...,...,...,...
319,Babylon,Damien Chazelle (director/screenplay); Brad Pi...,Drama Comedy,Damien Chazelle
320,Whitney Houston: I Wanna Dance with Somebody,Kasi Lemmons (director); Anthony McCarten (scr...,Music History Drama,Kasi Lemmons
321,The Pale Blue Eye,Scott Cooper (director/screenplay); Christian ...,Crime,Scott Cooper
322,Women Talking,Sarah Polley (director/screenplay); Rooney Mar...,Drama,Sarah Polley
323,A Man Called Otto,"Marc Forster (director), David Magee (screenpl...",Comedy Drama,Marc Forster

In [193]:
df_2022['actor_1_name'] = df_2022['Cast and crew'].map(lambda x: get_actor1_1(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\3696505166.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['actor_1_name'] = df_2022['Cast and crew'].map(lambda x: get_actor1_1(x))

In [194]:
df_2022['actor_2_name'] = df_2022['Cast and crew'].map(lambda x: get_actor2_2(x))
df_2022['actor_3_name'] = df_2022['Cast and crew'].map(lambda x: get_actor3_3(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1279649448.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['actor_2_name'] = df_2022['Cast and crew'].map(lambda x: get_actor2_2(x))
C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1279649448.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['actor_3_name'] = df_2022['Cast and crew'].map(lambda x: get_actor3_3(x))

In [195]:
df_2022

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,The 355,Simon Kinberg (director/screenplay); Theresa R...,Action Thriller,Simon Kinberg,Jessica Chastain,Lupita Nyong'o,PenÃ©lope Cruz
1,The Legend of La Llorona,Patricia Harris Seeley (director/screenplay); ...,Family Animation Fantasy Horror,Patricia Harris Seeley,Autumn Reeser,Antonio Cupo,Danny Trejo
2,The Commando,Asif Akbar (director); Koji Steven Sakai (scre...,Action Crime Thriller,Asif Akbar,Mickey Rourke,Michael Jai White,NaN
3,American Siege,Edward Drake (director/screenplay); Timothy V....,Action Adventure Thriller,Edward Drake,Timothy V. Murphy,Bruce Willis,NaN
4,Scream,"Matt Bettinelli-Olpin, Tyler Gillett (director...",Horror Mystery Thriller,"Matt Bettinelli-Olpin, Tyler Gillett",Melissa Barrera,Mason Gooding,Jenna Ortega
...,...,...,...,...,...,...,...
319,Babylon,Damien Chazelle (director/screenplay); Brad Pi...,Drama Comedy,Damien Chazelle,Brad Pitt,Margot Robbie,Diego Calva
320,Whitney Houston: I Wanna Dance with Somebody,Kasi Lemmons (director); Anthony McCarten (scr...,Music History Drama,Kasi Lemmons,Naomi Ackie,Stanley Tucci,Ashton Sanders
321,The Pale Blue Eye,Scott Cooper (director/screenplay); Christian ...,Crime,Scott Cooper,Christian Bale,Harry Melling,Gillian Anderson
322,Women Talking,Sarah Polley (director/screenplay); Rooney Mar...,Drama,Sarah Polley,Rooney Mara,Claire Foy,Jessie Buckley
323,A Man Called Otto,"Marc Forster (director), David Magee (screenpl...",Comedy Drama,Marc Forster,Tom Hanks,Mariana TreviÃ±o,Rachel Keller

In [196]:
df_2022 = df_2022.rename(columns={'Title':'movie_title'})

In [197]:
new_df22 = df_2022.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [198]:
new_df22

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Simon Kinberg,Jessica Chastain,Lupita Nyong'o,PenÃ©lope Cruz,Action Thriller,The 355
1,Patricia Harris Seeley,Autumn Reeser,Antonio Cupo,Danny Trejo,Family Animation Fantasy Horror,The Legend of La Llorona
2,Asif Akbar,Mickey Rourke,Michael Jai White,NaN,Action Crime Thriller,The Commando
3,Edward Drake,Timothy V. Murphy,Bruce Willis,NaN,Action Adventure Thriller,American Siege
4,"Matt Bettinelli-Olpin, Tyler Gillett",Melissa Barrera,Mason Gooding,Jenna Ortega,Horror Mystery Thriller,Scream
...,...,...,...,...,...,...
319,Damien Chazelle,Brad Pitt,Margot Robbie,Diego Calva,Drama Comedy,Babylon
320,Kasi Lemmons,Naomi Ackie,Stanley Tucci,Ashton Sanders,Music History Drama,Whitney Houston: I Wanna Dance with Somebody
321,Scott Cooper,Christian Bale,Harry Melling,Gillian Anderson,Crime,The Pale Blue Eye
322,Sarah Polley,Rooney Mara,Claire Foy,Jessie Buckley,Drama,Women Talking
323,Marc Forster,Tom Hanks,Mariana TreviÃ±o,Rachel Keller,Comedy Drama,A Man Called Otto

In [199]:
new_df22['actor_2_name'] = new_df22['actor_2_name'].replace(np.nan, 'unknown')
new_df22['actor_3_name'] = new_df22['actor_3_name'].replace(np.nan, 'unknown')

In [200]:
new_df22['movie_title'] = new_df22['movie_title'].str.lower()

In [201]:
new_df22['comb'] = new_df22['actor_1_name'] + ' ' + new_df21['actor_2_name'] + ' '+ new_df22['actor_3_name'] + ' '+ new_df22['director_name'] +' ' + new_df22['genres']

In [202]:
new_df22

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Simon Kinberg,Jessica Chastain,Lupita Nyong'o,PenÃ©lope Cruz,Action Thriller,the 355,Jessica Chastain Lupita Nyong'o PenÃ©lope Cruz ...
1,Patricia Harris Seeley,Autumn Reeser,Antonio Cupo,Danny Trejo,Family Animation Fantasy Horror,the legend of la llorona,Autumn Reeser Antonio Cupo Danny Trejo Patrici...
2,Asif Akbar,Mickey Rourke,Michael Jai White,unknown,Action Crime Thriller,the commando,Mickey Rourke Michael Jai White unknown Asif A...
3,Edward Drake,Timothy V. Murphy,Bruce Willis,unknown,Action Adventure Thriller,american siege,Timothy V. Murphy Bruce Willis unknown Edward ...
4,"Matt Bettinelli-Olpin, Tyler Gillett",Melissa Barrera,Mason Gooding,Jenna Ortega,Horror Mystery Thriller,scream,Melissa Barrera Mason Gooding Jenna Ortega Mat...
...,...,...,...,...,...,...,...
319,Damien Chazelle,Brad Pitt,Margot Robbie,Diego Calva,Drama Comedy,babylon,Brad Pitt Margot Robbie Diego Calva Damien Cha...
320,Kasi Lemmons,Naomi Ackie,Stanley Tucci,Ashton Sanders,Music History Drama,whitney houston: i wanna dance with somebody,Naomi Ackie Stanley Tucci Ashton Sanders Kasi ...
321,Scott Cooper,Christian Bale,Harry Melling,Gillian Anderson,Crime,the pale blue eye,Christian Bale Harry Melling Gillian Anderson ...
322,Sarah Polley,Rooney Mara,Claire Foy,Jessie Buckley,Drama,women talking,Rooney Mara Claire Foy Jessie Buckley Sarah Po...
323,Marc Forster,Tom Hanks,Mariana TreviÃ±o,Rachel Keller,Comedy Drama,a man called otto,Tom Hanks Mariana TreviÃ±o Rachel Keller Marc F...

## Extracting features of 2023 movies from Wikipedia

In [203]:
link6 = "https://en.wikipedia.org/wiki/List_of_American_films_of_2023"

In [204]:
df1 = pd.read_html(link6, header=0)[2]
df2 = pd.read_html(link6, header=0)[3]
df3 = pd.read_html(link6, header=0)[4]
df4 = pd.read_html(link6, header=0)[5]

In [205]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1752420719.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [206]:
df

,Rank,Title,Distributor,Domestic gross,Opening,Opening.1,Production company,Cast and crew,Ref.
0,1.0,The Super Mario Bros. Movie*,Universal,"$560,893,170",NaN,NaN,NaN,NaN,NaN
1,2.0,Guardians of the Galaxy Vol. 3*,Disney,"$306,304,761",NaN,NaN,NaN,NaN,NaN
2,3.0,Ant-Man and the Wasp: Quantumania*,Disney,"$214,455,625",NaN,NaN,NaN,NaN,NaN
3,4.0,John Wick: Chapter 4*,Lionsgate,"$186,531,016",NaN,NaN,NaN,NaN,NaN
4,5.0,Creed III,MGM,"$156,248,615",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
184,NaN,The Expendables 4,NaN,NaN,S E P T E M B E R,22.0,Lionsgate / Millennium Media,"Scott Waugh (director); Spenser Cohen, Max Ada...",[110]
185,NaN,The Book of Clarence,NaN,NaN,S E P T E M B E R,22.0,Columbia Pictures / Legendary Entertainment,Jeymes Samuel (director/screenplay); LaKeith S...,[162]
186,NaN,Drive-Away Dolls,NaN,NaN,S E P T E M B E R,22.0,Focus Features / Working Title Films,Ethan Coen (director/screenplay); Tricia Cooke...,[163]
187,NaN,PAW Patrol: The Mighty Movie,NaN,NaN,S E P T E M B E R,29.0,Paramount Pictures / Nickelodeon Movies / Spin...,"Cal Brunker (director); Mckenna Grace, Taraji ...",[164]
188,NaN,The Creator,NaN,NaN,S E P T E M B E R,29.0,20th Century Studios / Regency Enterprises / E...,Gareth Edwards (director/screenplay); Chris We...,[165]

In [207]:
df.drop(df.index[0:10], inplace=True)

In [208]:
df

,Rank,Title,Distributor,Domestic gross,Opening,Opening.1,Production company,Cast and crew,Ref.
10,NaN,M3GAN,NaN,NaN,J A N U A R Y,6.0,Universal Pictures / Blumhouse Productions / A...,Gerard Johnstone (director); Akela Cooper (scr...,[3]
11,NaN,The Old Way,NaN,NaN,J A N U A R Y,6.0,Saban Films / Saturn Films,Brett Donowho (director); Carl W. Lucas (scree...,[4]
12,NaN,The Devil Conspiracy,NaN,NaN,J A N U A R Y,11.0,Samuel Goldwyn Films,Nathan Frankowski (director); Ed Alan (screenp...,[5]
13,NaN,Plane,NaN,NaN,J A N U A R Y,13.0,Lionsgate / MadRiver Pictures / Di Bonaventura...,Jean-FranÃ§ois Richet (director); Charles Cummi...,[6]
14,NaN,House Party,NaN,NaN,J A N U A R Y,13.0,Warner Bros. Pictures / New Line Cinema,"Calmatic (director); Jamal Olori, Stephen Glov...",[7]
...,...,...,...,...,...,...,...,...,...
184,NaN,The Expendables 4,NaN,NaN,S E P T E M B E R,22.0,Lionsgate / Millennium Media,"Scott Waugh (director); Spenser Cohen, Max Ada...",[110]
185,NaN,The Book of Clarence,NaN,NaN,S E P T E M B E R,22.0,Columbia Pictures / Legendary Entertainment,Jeymes Samuel (director/screenplay); LaKeith S...,[162]
186,NaN,Drive-Away Dolls,NaN,NaN,S E P T E M B E R,22.0,Focus Features / Working Title Films,Ethan Coen (director/screenplay); Tricia Cooke...,[163]
187,NaN,PAW Patrol: The Mighty Movie,NaN,NaN,S E P T E M B E R,29.0,Paramount Pictures / Nickelodeon Movies / Spin...,"Cal Brunker (director); Mckenna Grace, Taraji ...",[164]
188,NaN,The Creator,NaN,NaN,S E P T E M B E R,29.0,20th Century Studios / Regency Enterprises / E...,Gareth Edwards (director/screenplay); Chris We...,[165]

In [209]:
df['genres'] = df['Title'].map(lambda x: get_genre1(str(x)))

In [210]:
df_2023 = df[['Title','Cast and crew','genres']]

In [211]:
df_2023

,Title,Cast and crew,genres
10,M3GAN,Gerard Johnstone (director); Akela Cooper (scr...,Science Fiction Horror Comedy
11,The Old Way,Brett Donowho (director); Carl W. Lucas (scree...,Western
12,The Devil Conspiracy,Nathan Frankowski (director); Ed Alan (screenp...,Horror Fantasy Science Fiction Thriller
13,Plane,Jean-FranÃ§ois Richet (director); Charles Cummi...,Action Adventure Thriller
14,House Party,"Calmatic (director); Jamal Olori, Stephen Glov...",Comedy
...,...,...,...
184,The Expendables 4,"Scott Waugh (director); Spenser Cohen, Max Ada...",Action Adventure Thriller War
185,The Book of Clarence,Jeymes Samuel (director/screenplay); LaKeith S...,History Drama
186,Drive-Away Dolls,Ethan Coen (director/screenplay); Tricia Cooke...,Crime Comedy
187,PAW Patrol: The Mighty Movie,"Cal Brunker (director); Mckenna Grace, Taraji ...",Animation Family Comedy
188,The Creator,Gareth Edwards (director/screenplay); Chris We...,Science Fiction Action Thriller

In [212]:
df_2023['director_name'] = df_2023['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\1551818249.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023['director_name'] = df_2023['Cast and crew'].map(lambda x: get_director(str(x)))

In [213]:
df_2023['actor_1_name'] = df_2023['Cast and crew'].map(lambda x: get_actor1_1(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\4061781682.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023['actor_1_name'] = df_2023['Cast and crew'].map(lambda x: get_actor1_1(x))

In [214]:
df_2023['actor_2_name'] = df_2023['Cast and crew'].map(lambda x: get_actor2_2(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\4033021046.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023['actor_2_name'] = df_2023['Cast and crew'].map(lambda x: get_actor2_2(x))

In [215]:
df_2023['actor_3_name'] = df_2023['Cast and crew'].map(lambda x: get_actor3_3(x))

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\60191886.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023['actor_3_name'] = df_2023['Cast and crew'].map(lambda x: get_actor3_3(x))

In [216]:
df_2023 = df_2023.rename(columns={'Title':'movie_title'})

In [217]:
new_df23 = df_2023.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [218]:
nan_count = new_df23.isna().sum()
print(nan_count)

director_name    0
actor_1_name     0
actor_2_name     1
actor_3_name     9
genres           0
movie_title      0
dtype: int64

In [219]:
new_df23['actor_2_name'] = new_df23['actor_2_name'].replace(np.nan, 'unknown')
new_df23['actor_3_name'] = new_df23['actor_3_name'].replace(np.nan, 'unknown')

In [220]:
new_df23['movie_title'] = new_df23['movie_title'].str.lower()

In [221]:
new_df23['comb'] = new_df23['actor_1_name'] + ' ' + new_df23['actor_2_name'] + ' '+ new_df23['actor_3_name'] + ' '+ new_df23['director_name'] +' ' + new_df23['genres']

In [222]:
new_df23

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
10,Gerard Johnstone,Allison Williams,Violet McGraw,Amie Donald,Science Fiction Horror Comedy,m3gan,Allison Williams Violet McGraw Amie Donald Ger...
11,Brett Donowho,Nicolas Cage,Ryan Kiera Armstrong,unknown,Western,the old way,Nicolas Cage Ryan Kiera Armstrong unknown Bret...
12,Nathan Frankowski,Alice Orr-Ewing,Joe Doyle,Eveline Hall,Horror Fantasy Science Fiction Thriller,the devil conspiracy,Alice Orr-Ewing Joe Doyle Eveline Hall Nathan ...
13,Jean-FranÃ§ois Richet,Gerard Butler,Mike Colter,Yoson An,Action Adventure Thriller,plane,Gerard Butler Mike Colter Yoson An Jean-FranÃ§o...
14,Calmatic,Tosin Cole,Jacob Latimore,Karen Obilom,Comedy,house party,Tosin Cole Jacob Latimore Karen Obilom Calmati...
...,...,...,...,...,...,...,...
184,Scott Waugh,Jason Statham,50 Cent,Megan Fox,Action Adventure Thriller War,the expendables 4,Jason Statham 50 Cent Megan Fox Scott Waugh Ac...
185,Jeymes Samuel,LaKeith Stanfield,Omar Sy,RJ Cyler,History Drama,the book of clarence,LaKeith Stanfield Omar Sy RJ Cyler Jeymes Samu...
186,Ethan Coen,Margaret Qualley,Geraldine Viswanathan,Beanie Feldstein,Crime Comedy,drive-away dolls,Margaret Qualley Geraldine Viswanathan Beanie ...
187,Cal Brunker,Cal Brunker (director); Mckenna Grace,Taraji P. Henson,Marsai Martin,Animation Family Comedy,paw patrol: the mighty movie,Cal Brunker (director); Mckenna Grace Taraji P...
188,Gareth Edwards,John David Washington,Gemma Chan,Ken Watanabe,Science Fiction Action Thriller,the creator,John David Washington Gemma Chan Ken Watanabe ...

In [225]:
combined_df = pd.concat([new_df23, new_df22], axis=0)

In [226]:
combined_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
10,Gerard Johnstone,Allison Williams,Violet McGraw,Amie Donald,Science Fiction Horror Comedy,m3gan,Allison Williams Violet McGraw Amie Donald Ger...
11,Brett Donowho,Nicolas Cage,Ryan Kiera Armstrong,unknown,Western,the old way,Nicolas Cage Ryan Kiera Armstrong unknown Bret...
12,Nathan Frankowski,Alice Orr-Ewing,Joe Doyle,Eveline Hall,Horror Fantasy Science Fiction Thriller,the devil conspiracy,Alice Orr-Ewing Joe Doyle Eveline Hall Nathan ...
13,Jean-FranÃ§ois Richet,Gerard Butler,Mike Colter,Yoson An,Action Adventure Thriller,plane,Gerard Butler Mike Colter Yoson An Jean-FranÃ§o...
14,Calmatic,Tosin Cole,Jacob Latimore,Karen Obilom,Comedy,house party,Tosin Cole Jacob Latimore Karen Obilom Calmati...
...,...,...,...,...,...,...,...
319,Damien Chazelle,Brad Pitt,Margot Robbie,Diego Calva,Drama Comedy,babylon,Brad Pitt Margot Robbie Diego Calva Damien Cha...
320,Kasi Lemmons,Naomi Ackie,Stanley Tucci,Ashton Sanders,Music History Drama,whitney houston: i wanna dance with somebody,Naomi Ackie Stanley Tucci Ashton Sanders Kasi ...
321,Scott Cooper,Christian Bale,Harry Melling,Gillian Anderson,Crime,the pale blue eye,Christian Bale Harry Melling Gillian Anderson ...
322,Sarah Polley,Rooney Mara,Claire Foy,Jessie Buckley,Drama,women talking,Rooney Mara Claire Foy Jessie Buckley Sarah Po...
323,Marc Forster,Tom Hanks,Mariana TreviÃ±o,Rachel Keller,Comedy Drama,a man called otto,Tom Hanks Mariana TreviÃ±o Rachel Keller Marc F...

In [227]:
my_df = new_df22.append(new_df23,ignore_index=True)

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\2867938759.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  my_df = new_df22.append(new_df23,ignore_index=True)

In [228]:
my_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Simon Kinberg,Jessica Chastain,Lupita Nyong'o,PenÃ©lope Cruz,Action Thriller,the 355,Jessica Chastain Lupita Nyong'o PenÃ©lope Cruz ...
1,Patricia Harris Seeley,Autumn Reeser,Antonio Cupo,Danny Trejo,Family Animation Fantasy Horror,the legend of la llorona,Autumn Reeser Antonio Cupo Danny Trejo Patrici...
2,Asif Akbar,Mickey Rourke,Michael Jai White,unknown,Action Crime Thriller,the commando,Mickey Rourke Michael Jai White unknown Asif A...
3,Edward Drake,Timothy V. Murphy,Bruce Willis,unknown,Action Adventure Thriller,american siege,Timothy V. Murphy Bruce Willis unknown Edward ...
4,"Matt Bettinelli-Olpin, Tyler Gillett",Melissa Barrera,Mason Gooding,Jenna Ortega,Horror Mystery Thriller,scream,Melissa Barrera Mason Gooding Jenna Ortega Mat...
...,...,...,...,...,...,...,...
498,Scott Waugh,Jason Statham,50 Cent,Megan Fox,Action Adventure Thriller War,the expendables 4,Jason Statham 50 Cent Megan Fox Scott Waugh Ac...
499,Jeymes Samuel,LaKeith Stanfield,Omar Sy,RJ Cyler,History Drama,the book of clarence,LaKeith Stanfield Omar Sy RJ Cyler Jeymes Samu...
500,Ethan Coen,Margaret Qualley,Geraldine Viswanathan,Beanie Feldstein,Crime Comedy,drive-away dolls,Margaret Qualley Geraldine Viswanathan Beanie ...
501,Cal Brunker,Cal Brunker (director); Mckenna Grace,Taraji P. Henson,Marsai Martin,Animation Family Comedy,paw patrol: the mighty movie,Cal Brunker (director); Mckenna Grace Taraji P...
502,Gareth Edwards,John David Washington,Gemma Chan,Ken Watanabe,Science Fiction Action Thriller,the creator,John David Washington Gemma Chan Ken Watanabe ...

In [229]:
old_df = pd.read_csv('new_data.csv')

In [230]:
old_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
5359,Jim Strouse,Jessica Williams,Chris O'Dowd,Keith Stanfield,Romance Comedy,the incredible jessica james,Jessica Williams Chris O'Dowd Keith Stanfield ...
5360,Farhad Mann,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Romance,can't buy my love,Adelaide Kane Benjamin Hollingsworth Jean Loui...
5361,Hannaleena Hauru,Inka HaapamÃ¤ki,Rosa Honkonen,Tiitus Rantala,Romance Comedy,thick lashes of lauri mÃ¤ntyvaara,Inka HaapamÃ¤ki Rosa Honkonen Tiitus Rantala Ha...
5362,Jonathan A. Rosenbaum,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Crime Comedy Action Family,cop and a half: new recruit,Lou Diamond Phillips Wallace Shawn Gina Holden...
5363,Ravi Udyawar,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Crime Drama Thriller,mom,Sridevi Kapoor Sajal Ali Akshaye Khanna Ravi U...

In [232]:
combined_df = df1.append([new_df18, new_df19,new_df20 , new_df21, new_df22 , new_df23], ignore_index=True)

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\334526874.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_df = df1.append([new_df18, new_df19,new_df20 , new_df21, new_df22 , new_df23], ignore_index=True)

In [233]:
combined_df

,Rank,Title,Distributor,Domestic gross,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,1.0,The Super Mario Bros. Movie*,Universal,"$560,893,170",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Guardians of the Galaxy Vol. 3*,Disney,"$306,304,761",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Ant-Man and the Wasp: Quantumania*,Disney,"$214,455,625",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,John Wick: Chapter 4*,Lionsgate,"$186,531,016",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Creed III,MGM,"$156,248,615",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1598,NaN,NaN,NaN,NaN,Scott Waugh,Jason Statham,50 Cent,Megan Fox,Action Adventure Thriller War,the expendables 4,Jason Statham 50 Cent Megan Fox Scott Waugh Ac...
1599,NaN,NaN,NaN,NaN,Jeymes Samuel,LaKeith Stanfield,Omar Sy,RJ Cyler,History Drama,the book of clarence,LaKeith Stanfield Omar Sy RJ Cyler Jeymes Samu...
1600,NaN,NaN,NaN,NaN,Ethan Coen,Margaret Qualley,Geraldine Viswanathan,Beanie Feldstein,Crime Comedy,drive-away dolls,Margaret Qualley Geraldine Viswanathan Beanie ...
1601,NaN,NaN,NaN,NaN,Cal Brunker,Cal Brunker (director); Mckenna Grace,Taraji P. Henson,Marsai Martin,Animation Family Comedy,paw patrol: the mighty movie,Cal Brunker (director); Mckenna Grace Taraji P...
1602,NaN,NaN,NaN,NaN,Gareth Edwards,John David Washington,Gemma Chan,Ken Watanabe,Science Fiction Action Thriller,the creator,John David Washington Gemma Chan Ken Watanabe ...

In [234]:
final_df = old_df.append(combined_df,ignore_index=True)

C:\Users\Yassine\AppData\Local\Temp\ipykernel_13028\4181883658.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = old_df.append(combined_df,ignore_index=True)

In [235]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb,Rank,Title,Distributor,Domestic gross
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...,NaN,NaN,NaN,NaN
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...,NaN,NaN,NaN,NaN
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...,NaN,NaN,NaN,NaN
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...,NaN,NaN,NaN,NaN
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
6962,Scott Waugh,Jason Statham,50 Cent,Megan Fox,Action Adventure Thriller War,the expendables 4,Jason Statham 50 Cent Megan Fox Scott Waugh Ac...,NaN,NaN,NaN,NaN
6963,Jeymes Samuel,LaKeith Stanfield,Omar Sy,RJ Cyler,History Drama,the book of clarence,LaKeith Stanfield Omar Sy RJ Cyler Jeymes Samu...,NaN,NaN,NaN,NaN
6964,Ethan Coen,Margaret Qualley,Geraldine Viswanathan,Beanie Feldstein,Crime Comedy,drive-away dolls,Margaret Qualley Geraldine Viswanathan Beanie ...,NaN,NaN,NaN,NaN
6965,Cal Brunker,Cal Brunker (director); Mckenna Grace,Taraji P. Henson,Marsai Martin,Animation Family Comedy,paw patrol: the mighty movie,Cal Brunker (director); Mckenna Grace Taraji P...,NaN,NaN,NaN,NaN
6966,Gareth Edwards,John David Washington,Gemma Chan,Ken Watanabe,Science Fiction Action Thriller,the creator,John David Washington Gemma Chan Ken Watanabe ...,NaN,NaN,NaN,NaN

In [236]:
final_df.to_csv('main_data.csv',index=False)